name: Build and Archive Workflow

on: [push]

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run PyInstaller
      run: python -m PyInstaller BenefitCostRatioCalcApp.spec # Replace with your .spec file's name

    - name: Archive dist folder using PowerShell
      run: |
        Compress-Archive -Path dist\* -DestinationPath dist.zip
      shell: pwsh

    - name: List files in directory
      run: Get-ChildItem
      shell: pwsh

    - name: Upload dist.zip as artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-folder
        path: dist.zip
        if-no-files-found: warn
