name: Build Python to EXE

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install uuid

    # If you have other dependencies in a requirements.txt file, uncomment below:
    # - name: Install project dependencies
    #   run: pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller main.py

    - name: Archive dist folder using PowerShell
      run: |
        Compress-Archive -Path dist\* -DestinationPath dist.zip
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-folder
        path: dist.tar.gz
